name: Metrics

on:
  schedule: [{cron: "0 * * * *"}] # Atualiza todo início de hora
  workflow_dispatch:             # Permite execução manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: America/Fortaleza
