name: Metrics

on:
  schedule: [{cron: "0 * * * *"}] # Atualiza todo início de hora
  workflow_dispatch:             # Permite execução manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependências necessárias
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd
          sudo apt-get install -y docker.io jq

      - uses: lowlighter/metrics@v3.23
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: America/Fortaleza
